# Generated by Django 3.1 on 2020-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('ID_SISTEMA', models.IntegerField(db_column='ID_SISTEMA', primary_key=True, serialize=False)),
                ('Descricao', models.TextField(db_column='DSC_SISTEMA', max_length=100, null=True)),
                ('DataInclusao', models.DateField(auto_now=True, db_column='DT_INCLUSAO')),
                ('ChaveInclusao', models.CharField(db_column='CHAVE_INCLUSAO', max_length=50, null=True)),
                ('DataAlteracao', models.DateField(db_column='DT_ALTERACAO', null=True)),
                ('ChaveAlteracao', models.CharField(db_column='CHAVE_ALTERACAO', max_length=50, null=True)),
                ('Excluido', models.CharField(db_column='FLAG_EXCLUIDO', default='N', max_length=1)),
                ('Tag', models.CharField(db_column='TAG_SISTEMA', max_length=50)),
            ],
            options={
                'db_table': 'MOBILE_CA_SISTEMA',
            },
        ),
    ]
