# Generated by Django 3.1 on 2020-08-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='ChaveInclusao',
            field=models.CharField(db_column='CHAVE_INCLUSAO', max_length=50),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='Excluido',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], db_column='FLAG_EXCLUIDO', default='N', max_length=1),
        ),
    ]
